languaje: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run test
- npm run build
deploy:
  provider: npm
  email: j.pichardo@tuta.io
  api_key:
    secure: L7JJg59+41EvD3AFY0/y8yCp2jrCNG6ZiZuJqteFdgM99IVp+ZKJlLrQjqfJQyFDqDpCAgQ0lQxkkLUeBmg+ThcPzXFYXY8nO+ymfPlPKtTLkjpOU2CgDernAz+QiEtWqHYDRKv3uqVbPihuSM/BgPKh0gWbt/Z1rfQrVnbS2h8VR/dcXuHvQtzGWkbOhgYFSfphtJoquHM5UAVn5GR9rni4UbAna1s//lf2CZQT3NUv6oYptd96rg522t/zxzHKzRqsOfXR/WV6zYaDYUs1/fcDTAzSZ/3v62/vXfJklXpcMJlHkuMQKTVxFSI7qKLhNHnSaUL1XPHNYXF6gtPqr5VV2bpf69ebs8bHaHyFwZIkmw/1R07UadFR+rDbIKqKZnuRP1BG6maIq1/bfkk47V8bYpHdp3GxmGU/Q0pWOplNJKMQAc3bcl9sOd7fBSJ5yGt7V8mPuCmMbQd6rfDndFVvfkUAfuhnHMv7llXPMWErrkGwYHQCrk8MS/qCXcpkXhBctg0NrqjR7W+aTetLFg0eWUfAIklgeSyFZCU4yq0wgU/T6SkyKcHwMWG5ukvQbwHMwO1y2215qStIRdEsZd5ASqqQzqyNXkm4T6IQ/t+HB+1wfoPfRyXDbAOS2uCKW/YSi8g+AqM0iH/CXRKFZcsGDA2+HhF92zizDKaf5Bc=
  on:
    tags: true
